service: serverless-nest-example
# serviceの記載方法が v3から変わる
# service:
#   name: serverless-nest-example

frameworkVersion: "3"

plugins:
  ##- '@hewmen/serverless-plugin-typescript'
  - 'serverless-plugin-typescript'
  - serverless-plugin-optimize
  - serverless-offline
  # - serverless-plugin-warmup

# custom:
#   # Enable warmup on all functions (only for production and staging)
#   warmup:      
#       - production
#       - staging

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  
package:
  individually: true

functions:
  main:
    handler: src/main.handler
    events:
      - http:
          method: ANY
          path: /{proxy+}
