service: serverless-nest-example
# serviceの記載方法が v3から変わる
# service:
#   name: serverless-nest-example

frameworkVersion: "3"

plugins:
  - '@hewmen/serverless-plugin-typescript'
  ##- 'serverless-plugin-typescript'
  - serverless-plugin-optimize
  - serverless-offline
  # - serverless-plugin-warmup

# custom:
#   # Enable warmup on all functions (only for production and staging)
#   warmup:      
#       - production
#       - staging

provider:
  name: aws
  runtime: nodejs18.x

package:
  individually: true

functions:
  main:
    handler: src/main.handler
    events:
      - http:
          method: any
          path: /{proxy+}
